name: Dead-Hosts Launcher deployment Workflow
on:
  push:
    branches:
      - master
      - "*"
  workflow_dispatch: {}

jobs:
  lint:
    name: Lint Dead-Hosts Launcher

    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.12"
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Clone repository

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          pip install pylint
          pip install .

      - name: Lint Dead-Hosts Launcher with Pylint
        run: pylint dead_hosts

  run:
    needs: lint
    name: "Run Dead-Hosts Launcher and check behaviors"

    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.12"
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Clone repository

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          pip install .

      - name: Prepare Launcher settings
        run: |
          cp ${{ github.workspace }}/info.example.json ${{ github.workspace }}/info.json

      - name: Launch the launcher
        run: |
          dead-hosts-launcher

      - name: Look for changes in info file
        run: |
          cat ${{ github.workspace }}/info.json

      - name: Look for changes in clean file
        run: |
          cat ${{ github.workspace }}/clean.list || true

  deploy_pypi:
    needs: run
    name: "Deploy 📦 to the PyPi"

    environment: release
    permissions:
      id-token: write

    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.12"
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Clone repository

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          pip install twine wheel setuptools

      - name: Build 📦
        run: |
          python setup.py sdist bdist_wheel

      - name: Check 📦
        run: |
          twine check dist/*

      - name: Publish 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip_existing: true
